using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CAT_Library.ft_Excel
{
    /// <summary>
    /// 
    /// </summary>
    public class LetterColumns
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="num"></param>
        /// <returns></returns>
        public string InLetter(string num)
        {
            string res, dec = "";
            Int64 entero;
            double nro;

            try
            {
                nro = Convert.ToDouble(num);
            }
            catch
            {
                return "";
            }

            entero = Convert.ToInt64(Math.Truncate(nro));

            res = ToText(Convert.ToDouble(entero)) + dec;
            return res;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public string ToText(double value)
        {
            string Num2Text = "";
            value = Math.Truncate(value);
            if (value == 1) Num2Text = "A";
            else if (value == 2) Num2Text = "B";
            else if (value == 3) Num2Text = "C";
            else if (value == 4) Num2Text = "D";
            else if (value == 5) Num2Text = "E";
            else if (value == 6) Num2Text = "F";
            else if (value == 7) Num2Text = "G";
            else if (value == 8) Num2Text = "H";
            else if (value == 9) Num2Text = "I";
            else if (value == 10) Num2Text = "J";
            else if (value == 11) Num2Text = "K";
            else if (value == 12) Num2Text = "L";
            else if (value == 13) Num2Text = "M";
            else if (value == 14) Num2Text = "N";
            else if (value == 15) Num2Text = "O";
            else if (value == 16) Num2Text = "P";
            else if (value == 17) Num2Text = "Q";
            else if (value == 18) Num2Text = "R";
            else if (value == 19) Num2Text = "S";
            else if (value == 20) Num2Text = "T";
            else if (value == 21) Num2Text = "U";
            else if (value == 22) Num2Text = "V";
            else if (value == 23) Num2Text = "W";
            else if (value == 24) Num2Text = "X";
            else if (value == 25) Num2Text = "Y";
            else if (value == 26) Num2Text = "Z";
            else if (value == 27) Num2Text = "AA";
            else if (value == 28) Num2Text = "AB";
            else if (value == 29) Num2Text = "AC";
            else if (value == 30) Num2Text = "AD";
            else if (value == 31) Num2Text = "AE";
            else if (value == 32) Num2Text = "AF";
            else if (value == 33) Num2Text = "AG";
            else if (value == 34) Num2Text = "AH";
            else if (value == 35) Num2Text = "AI";
            else if (value == 36) Num2Text = "AJ";
            else if (value == 37) Num2Text = "AK";
            else if (value == 38) Num2Text = "AL";
            else if (value == 39) Num2Text = "AM";
            else if (value == 40) Num2Text = "AN";
            else if (value == 41) Num2Text = "AO";
            else if (value == 42) Num2Text = "AP";
            else if (value == 43) Num2Text = "AQ";
            else if (value == 44) Num2Text = "AR";
            else if (value == 45) Num2Text = "AS";
            else if (value == 46) Num2Text = "AT";
            else if (value == 47) Num2Text = "AU";
            else if (value == 48) Num2Text = "AV";
            else if (value == 49) Num2Text = "AW";
            else if (value == 50) Num2Text = "AX";
            else if (value == 51) Num2Text = "AY";
            else if (value == 52) Num2Text = "AZ";
            else if (value == 53) Num2Text = "BA";
            else if (value == 54) Num2Text = "BB";
            else if (value == 55) Num2Text = "BC";
            else if (value == 56) Num2Text = "BD";
            else if (value == 57) Num2Text = "BE";
            else if (value == 58) Num2Text = "BF";
            else if (value == 59) Num2Text = "BG";
            else if (value == 60) Num2Text = "BH";
            else if (value == 61) Num2Text = "BI";
            else if (value == 62) Num2Text = "BJ";
            else if (value == 63) Num2Text = "BK";
            else if (value == 64) Num2Text = "BL";
            else if (value == 65) Num2Text = "BM";
            else if (value == 66) Num2Text = "BN";
            else if (value == 67) Num2Text = "BO";
            else if (value == 68) Num2Text = "BP";
            else if (value == 69) Num2Text = "BQ";
            else if (value == 70) Num2Text = "BR";
            else if (value == 71) Num2Text = "BS";
            else if (value == 72) Num2Text = "BT";
            else if (value == 73) Num2Text = "BU";
            else if (value == 74) Num2Text = "BV";
            else if (value == 75) Num2Text = "BW";
            else if (value == 76) Num2Text = "BX";
            else if (value == 77) Num2Text = "BY";
            else if (value == 78) Num2Text = "BZ";
            else if (value == 79) Num2Text = "CA";
            else if (value == 80) Num2Text = "CB";
            else if (value == 81) Num2Text = "CC";
            else if (value == 82) Num2Text = "CD";
            else if (value == 83) Num2Text = "CE";
            else if (value == 84) Num2Text = "CF";
            else if (value == 85) Num2Text = "CG";
            else if (value == 86) Num2Text = "CH";
            else if (value == 87) Num2Text = "CI";
            else if (value == 88) Num2Text = "CJ";
            else if (value == 89) Num2Text = "CK";
            else if (value == 90) Num2Text = "CL";
            else if (value == 91) Num2Text = "CM";
            else if (value == 92) Num2Text = "CN";
            else if (value == 93) Num2Text = "CO";
            else if (value == 94) Num2Text = "CP";
            else if (value == 95) Num2Text = "CQ";
            else if (value == 96) Num2Text = "CR";
            else if (value == 97) Num2Text = "CS";
            else if (value == 98) Num2Text = "CT";
            else if (value == 99) Num2Text = "CU";
            else if (value == 100) Num2Text = "CV";
            else if (value == 101) Num2Text = "CW";
            else if (value == 102) Num2Text = "CX";
            else if (value == 103) Num2Text = "CY";
            else if (value == 104) Num2Text = "CZ";
            else if (value == 105) Num2Text = "DA";
            else if (value == 106) Num2Text = "DB";
            else if (value == 107) Num2Text = "DC";
            else if (value == 108) Num2Text = "DD";
            else if (value == 109) Num2Text = "DE";
            else if (value == 110) Num2Text = "DF";
            else if (value == 111) Num2Text = "DG";
            else if (value == 112) Num2Text = "DH";
            else if (value == 113) Num2Text = "DI";
            else if (value == 114) Num2Text = "DJ";
            else if (value == 115) Num2Text = "DK";
            else if (value == 116) Num2Text = "DL";
            else if (value == 117) Num2Text = "DM";
            else if (value == 118) Num2Text = "DN";
            else if (value == 119) Num2Text = "DO";
            else if (value == 120) Num2Text = "DP";
            else if (value == 121) Num2Text = "DQ";
            else if (value == 122) Num2Text = "DR";
            else if (value == 123) Num2Text = "DS";
            else if (value == 124) Num2Text = "DT";
            else if (value == 125) Num2Text = "DU";
            else if (value == 126) Num2Text = "DV";
            else if (value == 127) Num2Text = "DW";
            else if (value == 128) Num2Text = "DX";
            else if (value == 129) Num2Text = "DY";
            else if (value == 130) Num2Text = "DZ";
            else if (value == 131) Num2Text = "EA";
            else if (value == 132) Num2Text = "EB";
            else if (value == 133) Num2Text = "EC";
            else if (value == 134) Num2Text = "ED";
            else if (value == 135) Num2Text = "EE";
            else if (value == 136) Num2Text = "EF";
            else if (value == 137) Num2Text = "EG";
            else if (value == 138) Num2Text = "EH";
            else if (value == 139) Num2Text = "EI";
            else if (value == 140) Num2Text = "EJ";
            else if (value == 141) Num2Text = "EK";
            else if (value == 142) Num2Text = "EL";
            else if (value == 143) Num2Text = "EM";
            else if (value == 144) Num2Text = "EN";
            else if (value == 145) Num2Text = "EO";
            else if (value == 146) Num2Text = "EP";
            else if (value == 147) Num2Text = "EQ";
            else if (value == 148) Num2Text = "ER";
            else if (value == 149) Num2Text = "ES";
            else if (value == 150) Num2Text = "ET";
            else if (value == 151) Num2Text = "EU";
            else if (value == 152) Num2Text = "EV";
            else if (value == 153) Num2Text = "EW";
            else if (value == 154) Num2Text = "EX";
            else if (value == 155) Num2Text = "EY";
            else if (value == 156) Num2Text = "EZ";
            else if (value == 157) Num2Text = "FA";
            else if (value == 158) Num2Text = "FB";
            else if (value == 159) Num2Text = "FC";
            else if (value == 160) Num2Text = "FD";
            else if (value == 161) Num2Text = "FE";
            else if (value == 162) Num2Text = "FF";
            else if (value == 163) Num2Text = "FG";
            else if (value == 164) Num2Text = "FH";
            else if (value == 165) Num2Text = "FI";
            else if (value == 166) Num2Text = "FJ";
            else if (value == 167) Num2Text = "FK";
            else if (value == 168) Num2Text = "FL";
            else if (value == 169) Num2Text = "FM";
            else if (value == 170) Num2Text = "FN";
            else if (value == 171) Num2Text = "FO";
            else if (value == 172) Num2Text = "FP";
            else if (value == 173) Num2Text = "FQ";
            else if (value == 174) Num2Text = "FR";
            else if (value == 175) Num2Text = "FS";
            else if (value == 176) Num2Text = "FT";
            else if (value == 177) Num2Text = "FU";
            else if (value == 178) Num2Text = "FV";
            else if (value == 179) Num2Text = "FW";
            else if (value == 180) Num2Text = "FX";
            else if (value == 181) Num2Text = "FY";
            else if (value == 182) Num2Text = "FZ";
            else if (value == 183) Num2Text = "GA";
            else if (value == 184) Num2Text = "GB";
            else if (value == 185) Num2Text = "GC";
            else if (value == 186) Num2Text = "GD";
            else if (value == 187) Num2Text = "GE";
            else if (value == 188) Num2Text = "GF";
            else if (value == 189) Num2Text = "GG";
            else if (value == 190) Num2Text = "GH";
            else if (value == 191) Num2Text = "GI";
            else if (value == 192) Num2Text = "GJ";
            else if (value == 193) Num2Text = "GK";
            else if (value == 194) Num2Text = "GL";
            else if (value == 195) Num2Text = "GM";
            else if (value == 196) Num2Text = "GN";
            else if (value == 197) Num2Text = "GO";
            else if (value == 198) Num2Text = "GP";
            else if (value == 199) Num2Text = "GQ";
            else if (value == 200) Num2Text = "GR";
            else if (value == 201) Num2Text = "GS";
            else if (value == 202) Num2Text = "GT";
            else if (value == 203) Num2Text = "GU";
            else if (value == 204) Num2Text = "GV";
            else if (value == 205) Num2Text = "GW";
            else if (value == 206) Num2Text = "GX";
            else if (value == 207) Num2Text = "GY";
            else if (value == 208) Num2Text = "GZ";
            else if (value == 209) Num2Text = "HA";
            else if (value == 210) Num2Text = "HB";
            else if (value == 211) Num2Text = "HC";
            else if (value == 212) Num2Text = "HD";
            else if (value == 213) Num2Text = "HE";
            else if (value == 214) Num2Text = "HF";
            else if (value == 215) Num2Text = "HG";
            else if (value == 216) Num2Text = "HH";
            else if (value == 217) Num2Text = "HI";
            else if (value == 218) Num2Text = "HJ";
            else if (value == 219) Num2Text = "HK";
            else if (value == 220) Num2Text = "HL";
            else if (value == 221) Num2Text = "HM";
            else if (value == 222) Num2Text = "HN";
            else if (value == 223) Num2Text = "HO";
            else if (value == 224) Num2Text = "HP";
            else if (value == 225) Num2Text = "HQ";
            else if (value == 226) Num2Text = "HR";
            else if (value == 227) Num2Text = "HS";
            else if (value == 228) Num2Text = "HT";
            else if (value == 229) Num2Text = "HU";
            else if (value == 230) Num2Text = "HV";
            else if (value == 231) Num2Text = "HW";
            else if (value == 232) Num2Text = "HX";
            else if (value == 233) Num2Text = "HY";
            else if (value == 234) Num2Text = "HZ";
            else if (value == 235) Num2Text = "IA";
            else if (value == 236) Num2Text = "IB";
            else if (value == 237) Num2Text = "IC";
            else if (value == 238) Num2Text = "ID";
            else if (value == 239) Num2Text = "IE";
            else if (value == 240) Num2Text = "IF";
            else if (value == 241) Num2Text = "IG";
            else if (value == 242) Num2Text = "IH";
            else if (value == 243) Num2Text = "II";
            else if (value == 244) Num2Text = "IJ";
            else if (value == 245) Num2Text = "IK";
            else if (value == 246) Num2Text = "IL";
            else if (value == 247) Num2Text = "IM";
            else if (value == 248) Num2Text = "IN";
            else if (value == 249) Num2Text = "IO";
            else if (value == 250) Num2Text = "IP";
            else if (value == 251) Num2Text = "IQ";
            else if (value == 252) Num2Text = "IR";
            else if (value == 253) Num2Text = "IS";
            else if (value == 254) Num2Text = "IT";
            else if (value == 255) Num2Text = "IU";
            else if (value == 256) Num2Text = "IV";
            else if (value == 257) Num2Text = "IW";
            else if (value == 258) Num2Text = "IX";
            else if (value == 259) Num2Text = "IY";
            else if (value == 260) Num2Text = "IZ";
            else if (value == 261) Num2Text = "JA";
            else if (value == 262) Num2Text = "JB";
            else if (value == 263) Num2Text = "JC";
            else if (value == 264) Num2Text = "JD";
            else if (value == 265) Num2Text = "JE";
            else if (value == 266) Num2Text = "JF";
            else if (value == 267) Num2Text = "JG";
            else if (value == 268) Num2Text = "JH";
            else if (value == 269) Num2Text = "JI";
            else if (value == 270) Num2Text = "JJ";
            else if (value == 271) Num2Text = "JK";
            else if (value == 272) Num2Text = "JL";
            else if (value == 273) Num2Text = "JM";
            else if (value == 274) Num2Text = "JN";
            else if (value == 275) Num2Text = "JO";
            else if (value == 276) Num2Text = "JP";
            else if (value == 277) Num2Text = "JQ";
            else if (value == 278) Num2Text = "JR";
            else if (value == 279) Num2Text = "JS";
            else if (value == 280) Num2Text = "JT";
            else if (value == 281) Num2Text = "JU";
            else if (value == 282) Num2Text = "JV";
            else if (value == 283) Num2Text = "JW";
            else if (value == 284) Num2Text = "JX";
            else if (value == 285) Num2Text = "JY";
            else if (value == 286) Num2Text = "JZ";
            else if (value == 287) Num2Text = "KA";
            else if (value == 288) Num2Text = "KB";
            else if (value == 289) Num2Text = "KC";
            else if (value == 290) Num2Text = "KD";
            else if (value == 291) Num2Text = "KE";
            else if (value == 292) Num2Text = "KF";
            else if (value == 293) Num2Text = "KG";
            else if (value == 294) Num2Text = "KH";
            else if (value == 295) Num2Text = "KI";
            else if (value == 296) Num2Text = "KJ";
            else if (value == 297) Num2Text = "KK";
            else if (value == 298) Num2Text = "KL";
            else if (value == 299) Num2Text = "KM";
            else if (value == 300) Num2Text = "KN";
            else if (value == 301) Num2Text = "KO";
            else if (value == 302) Num2Text = "KP";
            else if (value == 303) Num2Text = "KQ";
            else if (value == 304) Num2Text = "KR";
            else if (value == 305) Num2Text = "KS";
            else if (value == 306) Num2Text = "KT";
            else if (value == 307) Num2Text = "KU";
            else if (value == 308) Num2Text = "KV";
            else if (value == 309) Num2Text = "KW";
            else if (value == 310) Num2Text = "KX";
            else if (value == 311) Num2Text = "KY";
            else if (value == 312) Num2Text = "KZ";
            else if (value == 313) Num2Text = "LA";
            else if (value == 314) Num2Text = "LB";
            else if (value == 315) Num2Text = "LC";
            else if (value == 316) Num2Text = "LD";
            else if (value == 317) Num2Text = "LE";
            else if (value == 318) Num2Text = "LF";
            else if (value == 319) Num2Text = "LG";
            else if (value == 320) Num2Text = "LH";
            else if (value == 321) Num2Text = "LI";
            else if (value == 322) Num2Text = "LJ";
            else if (value == 323) Num2Text = "LK";
            else if (value == 324) Num2Text = "LL";
            else if (value == 325) Num2Text = "LM";
            else if (value == 326) Num2Text = "LN";
            else if (value == 327) Num2Text = "LO";
            else if (value == 328) Num2Text = "LP";
            else if (value == 329) Num2Text = "LQ";
            else if (value == 330) Num2Text = "LR";
            else if (value == 331) Num2Text = "LS";
            else if (value == 332) Num2Text = "LT";
            else if (value == 333) Num2Text = "LU";
            else if (value == 334) Num2Text = "LV";
            else if (value == 335) Num2Text = "LW";
            else if (value == 336) Num2Text = "LX";
            else if (value == 337) Num2Text = "LY";
            else if (value == 338) Num2Text = "LZ";
            else if (value == 339) Num2Text = "MA";
            else if (value == 340) Num2Text = "MB";
            else if (value == 341) Num2Text = "MC";
            else if (value == 342) Num2Text = "MD";
            else if (value == 343) Num2Text = "ME";
            else if (value == 344) Num2Text = "MF";
            else if (value == 345) Num2Text = "MG";
            else if (value == 346) Num2Text = "MH";
            else if (value == 347) Num2Text = "MI";
            else if (value == 348) Num2Text = "MJ";
            else if (value == 349) Num2Text = "MK";
            else if (value == 350) Num2Text = "ML";
            else if (value == 351) Num2Text = "MM";
            else if (value == 352) Num2Text = "MN";
            else if (value == 353) Num2Text = "MO";
            else if (value == 354) Num2Text = "MP";
            else if (value == 355) Num2Text = "MQ";
            else if (value == 356) Num2Text = "MR";
            else if (value == 357) Num2Text = "MS";
            else if (value == 358) Num2Text = "MT";
            else if (value == 359) Num2Text = "MU";
            else if (value == 360) Num2Text = "MV";
            else if (value == 361) Num2Text = "MW";
            else if (value == 362) Num2Text = "MX";
            else if (value == 363) Num2Text = "MY";
            else if (value == 364) Num2Text = "MZ";
            else if (value == 365) Num2Text = "NA";
            else if (value == 366) Num2Text = "NB";
            else if (value == 367) Num2Text = "NC";
            else if (value == 368) Num2Text = "ND";
            else if (value == 369) Num2Text = "NE";
            else if (value == 370) Num2Text = "NF";
            else if (value == 371) Num2Text = "NG";
            else if (value == 372) Num2Text = "NH";
            else if (value == 373) Num2Text = "NI";
            else if (value == 374) Num2Text = "NJ";
            else if (value == 375) Num2Text = "NK";
            else if (value == 376) Num2Text = "NL";
            else if (value == 377) Num2Text = "NM";
            else if (value == 378) Num2Text = "NN";
            else if (value == 379) Num2Text = "NO";
            else if (value == 380) Num2Text = "NP";
            else if (value == 381) Num2Text = "NQ";
            else if (value == 382) Num2Text = "NR";
            else if (value == 383) Num2Text = "NS";
            else if (value == 384) Num2Text = "NT";
            else if (value == 385) Num2Text = "NU";
            else if (value == 386) Num2Text = "NV";
            else if (value == 387) Num2Text = "NW";
            else if (value == 388) Num2Text = "NX";
            else if (value == 389) Num2Text = "NY";
            else if (value == 390) Num2Text = "NZ";
            return Num2Text;
        }
    }
}
